name: searx_go
description: "SearxGo: Um buscador rápido, privado e customizável."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  # 📦 Dependências principais
  cupertino_icons: ^1.0.6
  http: ^1.2.0               # Motor de busca (API JSON)
  shared_preferences: ^2.2.2 # Persistência de configs
  fluttertoast: ^8.2.4       # Notificações
  flutter_phoenix: ^1.1.0    # Reset do app
  flutter_custom_tabs: ^2.0.0  # <-- ADICIONADO AQUI

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/searx.webp"
  adaptive_icon_background: "#118c89"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/searx.webp
